# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/imports/ARMSOC_1/arm_single.sv
  C:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/imports/ARMSOC_1/Software/imem.sv
  C:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/imports/Software/ahbrom.sv
}
read_verilog -library xil_defaultlib C:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/imports/ARMSOC_1/AHBLITE_SYS.v
read_ip -quiet C:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/ip/ClockDiv_2/ClockDiv.xci
set_property used_in_implementation false [get_files -all c:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/ip/ClockDiv_2/ClockDiv_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/ip/ClockDiv_2/ClockDiv.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/ip/ClockDiv_2/ClockDiv_ooc.xdc]
set_property is_locked true [get_files C:/Users/Mary/Documents/RISCME-master/ARMSOC_1/Xilinx/ARMSOC_1.srcs/sources_1/ip/ClockDiv_2/ClockDiv.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Mary/Documents/ZYBO-master/Resources/XDC/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Mary/Documents/ZYBO-master/Resources/XDC/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top AHBLITE_SYS -part xc7z010clg400-1


write_checkpoint -force -noxdef AHBLITE_SYS.dcp

catch { report_utilization -file AHBLITE_SYS_utilization_synth.rpt -pb AHBLITE_SYS_utilization_synth.pb }
