# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Mary/Documents/ZYBO-master/Resources/XDC/ZYBO_Master.xdc

# IP: ip/ClockDiv_2/ClockDiv.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ClockDiv || ORIG_REF_NAME==ClockDiv}]

# XDC: ip/ClockDiv_2/ClockDiv_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClockDiv || ORIG_REF_NAME==ClockDiv}] {/inst }]/inst ]]

# XDC: ip/ClockDiv_2/ClockDiv.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClockDiv || ORIG_REF_NAME==ClockDiv}] {/inst }]/inst ]]

# XDC: ip/ClockDiv_2/ClockDiv_ooc.xdc
